# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 19:34
from __future__ import unicode_literals
import pandas as pd
from classy.models import Classifier, Corpus


from django.db import migrations


def add_initial_data(apps, schema_editor):
    plc = Classifier(name='Programming Language')
    plc.save()

    raw_data = pd.read_csv('coding_data.csv',
                           names=['Language', 'Task', 'Code'])
    data = raw_data[raw_data['Code'] != '`PARSER ERROR']
    clean_data = pd.DataFrame({'Code': data['Code'],
                               'Language': data['Language'].str.lower(),
                               'Task': data['Task']})
    clean_data = clean_data.dropna()
    # clean_data.groupby('Language').size().sort_values()
    for index, row in clean_data.iterrows():
        corp = Corpus(classifier=plc,
                      category=row['Language'], text=row['Code'])
        corp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
