# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0003_classifier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
